file_format: "1"
id: corne
name: The corne 
type: shield
url: https://github.com/riyadahmed233/zmk-config-corne
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - corne_left
  - corne_right
  - corne_dongle
